/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "array.h"


void
arrsum_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	S  arraysum_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ARRSUM_PROG, ARRSUM_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	printf("Enter size\n");
	scanf("%d",&(arraysum_1_arg.size));
	
	for(int i=0; i<arraysum_1_arg.size; i++)
	{
		scanf("%d",&(arraysum_1_arg.a[i]));
	}

	result_1 = arraysum_1(&arraysum_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
		printf("Sum : %d\n", *result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	arrsum_prog_1 (host);
exit (0);
}
