/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ARRAY_H_RPCGEN
#define _ARRAY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct S {
	int size;
	int a[10];
};
typedef struct S S;

#define ARRSUM_PROG 0x12345678
#define ARRSUM_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ARRAYSUM 1
extern  int * arraysum_1(S *, CLIENT *);
extern  int * arraysum_1_svc(S *, struct svc_req *);
extern int arrsum_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ARRAYSUM 1
extern  int * arraysum_1();
extern  int * arraysum_1_svc();
extern int arrsum_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_S (XDR *, S*);

#else /* K&R C */
extern bool_t xdr_S ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ARRAY_H_RPCGEN */
