/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "array.h"

int *
arraysum_1_svc(S *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	int sz = argp->size;
	int sum=0;
	for(int i=0; i<sz; i++)
		sum+= argp->a[i];
	
	printf("Sum %d\n", sum);
	
	result = sum;


	return &result;
}
